@echo off

echo STRUCT_ID	SWISSPROTID	PDBID	TARGET_NAME	TARGET_CLASS	TARGET_BIOACTIVITY_VALUE	TARGET_BIOACTIVITY_TYPE	CONFIDENCE	DATA_SOURCE	ACTVSMEDI	ACTVSTSC	ACTVSBOTH > head1
cat head1 DRUG_TARGET.tab > tmp1
move tmp1 DRUG_TARGET.tab

echo STRUCT_ID	REF	ACT_TYPE	ACT_VAL > head1
cat head1 HERG_BIOACT.tab > tmp1
move tmp1 HERG_BIOACT.tab

echo STRUCT_ID	MIXTURE_ID	FILTER	DERIVATIVE	TRADE_NAME	CASNO	DRUG_CODE	MELTING_POINT > head1
cat head1 MIXTURE.tab > tmp1
move tmp1 MIXTURE.tab

echo MIXTURE_ID	VALUE	UNIT	TYPE	SPECIES	COMMENT > head1
cat head1 MIXTURE_LD50.tab > tmp1
move tmp1 MIXTURE_LD50.tab

echo MIXTURE_ID	VALUE	UNIT	COMMENT > head1
cat head1 MIXTURE_WATER_SOL.tab > tmp1
move tmp1 MIXTURE_WATER_SOL.tab

echo STRUCT_ID	NAME	SWISSPROTID > head1
cat head1 PHASE1_METAB_ENZYME.tab > tmp1
move tmp1 PHASE1_METAB_ENZYME.tab

echo STRUCT_ID	REF	TARGET_TYPE	TARGET_NAME	ACT_TYPE	ACT_VAL	INHIB_PERC	LIG_EFF > head1
cat head1 WOMBAT_ACTLIST.tab > tmp1
move tmp1 WOMBAT_ACTLIST.tab

echo STRUCT_ID	TRADE_NAME	YEAR	VALUE	REPORT_COMPANY > head1
cat head1 SALES.tab > tmp1
move tmp1 SALES.tab

del head1
